export const posts = [
  {
    _id: "62b9aeb8dd34989468b30fd6",
    index: 0,
    isActive: true,
    userImg:
      "https://images.pexels.com/photos/11293709/pexels-photo-11293709.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    name: "Kramer Haney",
    school: "Aquasseur University",
    email: "kramerhaney@aquasseur.com",
    desc: "Dolor ullamco irure cupidatat irure in ea mollit duis enim irure sit eiusmod fugiat magna. Fugiat non anim qui enim tempor laborum fugiat nulla mollit sit sit. Et quis ea magna consequat cupidatat ullamco ea consectetur adipisicing culpa ut ullamco. Mollit cillum non laboris aute et.\r\n",
    createdAt: "1590440124503",
    likesCount: 21,
    commentCount: 304,
  },
  {
    _id: "62b9aeb8299fb5e04e3f4a59",
    index: 1,
    isActive: true,
    userImg:
      "https://images.pexels.com/photos/11293709/pexels-photo-11293709.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    name: "Tracey Morin",
    school: "Kegular University",
    email: "traceymorin@kegular.com",
    desc: "Et in enim eu occaecat excepteur sit voluptate nostrud ea excepteur. Duis id do cupidatat deserunt duis amet elit. Nisi nostrud ea occaecat proident officia. Ipsum voluptate id aliqua qui minim occaecat amet mollit laboris quis excepteur. Amet reprehenderit est tempor aute est excepteur anim. Aliquip dolor eu cupidatat occaecat. Lorem proident sit qui dolor ipsum occaecat labore excepteur consequat sunt enim ad sunt enim.\r\n",
    createdAt: "1590440124503",
    likesCount: 145,
    commentCount: 540,
  },
  {
    _id: "62b9aeb8d47450e42a916c37",
    index: 2,
    isActive: false,
    userImg:
      "https://images.pexels.com/photos/11293709/pexels-photo-11293709.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    name: "Leonor Petersen",
    school: "Boilcat University",
    email: "leonorpetersen@boilcat.com",
    desc: "Sit minim sint aliquip veniam adipisicing officia aliquip. Ipsum proident aute mollit dolore ipsum cupidatat anim laborum Lorem. Incididunt commodo non enim est. Sit sint dolore reprehenderit sint dolore incididunt.\r\n",
    createdAt: "1590440124503",
    likesCount: 21,
    commentCount: 156,
  },
  {
    _id: "62b9aeb83937cb17a09968bb",
    index: 3,
    isActive: false,
    userImg:
      "https://images.pexels.com/photos/11293709/pexels-photo-11293709.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    name: "Autumn Wilkinson",
    school: "Accel University",
    email: "autumnwilkinson@accel.com",
    desc: "Velit tempor tempor anim qui officia officia occaecat reprehenderit sunt anim culpa tempor veniam ut. Amet quis anim sit aliquip eu et occaecat exercitation id. Officia in ut fugiat Lorem anim sit incididunt magna. Dolore minim do excepteur sit tempor veniam consectetur ea aute elit consectetur velit pariatur aliquip. Sit reprehenderit officia ipsum adipisicing ad. Duis consectetur consectetur eiusmod cillum nulla mollit.\r\n",
    createdAt: "1590440124503",
    likesCount: 17,
    commentCount: 717,
  },
  {
    _id: "62b9aeb894f1fa6d2e482d5d",
    index: 4,
    isActive: true,
    userImg:
      "https://images.pexels.com/photos/11293709/pexels-photo-11293709.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    name: "Carey Marks",
    school: "Steeltab University",
    email: "careymarks@steeltab.com",
    desc: "Amet non esse do laboris eu dolor. Consequat nulla non velit esse. Ea pariatur officia tempor exercitation magna amet tempor culpa amet cillum. Sint commodo proident fugiat quis minim irure labore incididunt nulla culpa cupidatat.\r\n",
    createdAt: "1590440124503",
    likesCount: 5,
    commentCount: 884,
  },
  {
    _id: "62b9aeb84eb792d681472181",
    index: 5,
    isActive: false,
    userImg:
      "https://images.pexels.com/photos/11293709/pexels-photo-11293709.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    name: "Thornton Compton",
    school: "Autograte University",
    email: "thorntoncompton@autograte.com",
    desc: "Proident nostrud adipisicing eiusmod cupidatat culpa labore aute pariatur cupidatat fugiat esse. Magna consequat exercitation magna aliquip fugiat voluptate amet anim. Aute excepteur irure non Lorem. Nulla quis sit elit ut nulla eu aute amet magna. Et magna sunt ea exercitation sunt aute.\r\n",
    createdAt: "1590440124503",
    likesCount: 7,
    commentCount: 229,
  },
  {
    _id: "62b9aeb83c739380d579c43d",
    index: 6,
    isActive: true,
    userImg:
      "https://images.pexels.com/photos/11293709/pexels-photo-11293709.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    name: "Pruitt Sampson",
    school: "Buzzopia University",
    email: "pruittsampson@buzzopia.com",
    desc: "Et irure labore fugiat eu amet pariatur non officia. Eiusmod nulla labore in enim aliquip deserunt. Cupidatat nisi sit enim consectetur. Incididunt excepteur labore consectetur incididunt reprehenderit duis.\r\n",
    createdAt: "1590440124503",
    likesCount: 10543,
    commentCount: 572,
  },
];
